### PR TITLE
fix(devtools): issue:#3445 chrome extension display incorrectly

### PR DESCRIPTION
**Pull request by fuzi1996**
_Before_ submitting a pull request, please make sure the following is done...

- [x] Ensure the pull request title and commit message follow the [Commit Specific](https://formilyjs.org/guide/contribution#pr-specification) in **English**.
- [ ] Fork the repo and create your branch from `master` or `formily_next`.
- [ ] If you've added code that should be tested, add tests!
- [ ] If you've changed APIs, update the documentation.
- [ ] Ensure the test suite passes (`npm test`).
- [ ] Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.

**Please do not delete the above content**

---

## What have you changed?

[issues/3445](https://github.com/alibaba/formily/issues/3445)

### CODE REVIEW

**Comment by janryWang** [comment]
changelog 不需要手动改

**Comment by fuzi1996** [comment]
> changelog 不需要手动改

就改个名字 😊

**Comment by janryWang** [comment]
> > changelog 不需要手动改
> 
> 就改个名字 😊

这是自动生成的。。。

**Comment by fuzi1996** [comment]
> > > changelog 不需要手动改
> > 
> > 
> > 就改个名字 😊
> 
> 这是自动生成的。。。

恢复了

**Comment by janryWang** [comment]
你只需要改react/react-dom 版本号就行了，其他都不需要改，yarn.lock 会自动更新都

**Pull request merged**
